spring:
  cloud:
    gateway:
      default-filters:
      routes:
        # =====================================
        - id: local_rate_limiter_config_test
          uri: http://localhost:9090
          predicates:
            - Path=/iproute/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                bucket4j-rate-limiter:
                  capacity: 3
                  period: 20s
                  requestedTokens: 1
debug: false
server:
  port: 9090
logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
