spring:
  application:
    name: ratelimitgatewaywithbucket4jspringbootstarter
  cache:
    type: hazelcast
  cloud:
    gateway:
      routes:
        - id: route1
          #uri: http://localhost:8089
          #uri: http://httpbin.org:80
          uri: http://localhost:9090
          predicates:
            - Path=/iproute/**
          filters:
            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: "*"
bucket4j:
  filter-config-caching-enabled: true
  filter-config-cache-name: filterConfigCache
  default-metric-tags:
    - expression: "1"
      key: xx
  filters:
    - id: filter1
      major-version: 1
      metrics:
        types:
          - consumed-counter
          - rejected-counter
        tags:
          - key: xx
            expression: "2"
      cache-name: buckets
      filter-method: gateway
      url: .*
      filter-order: -100000
      rate-limits:
        - tokens-inheritance-strategy: reset
          bandwidths:
            - capacity: 5
              time: 10
              unit: seconds
              refill-speed: interval
            - capacity: 43200
              time: 1
              unit: days
              refill-speed: interval
debug: false
server:
  port: 9090

logging:
  level:
    com.giffing.bucket4j.spring.boot.starter: debug